# Generated by Django 4.0.3 on 2022-04-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
    ]
