# Generated by Django 4.0.3 on 2022-04-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_links_alter_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='links',
            field=models.TextField(),
        ),
    ]
