# Generated by Django 4.0.3 on 2022-08-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='level',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(default='null', upload_to='thumb/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(default='', upload_to='books/%y/%m/%d'),
        ),
    ]
