# Generated by Django 4.0.3 on 2022-08-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_post_level_post_thumbnail_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='books/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(default='', upload_to='thumb/%y/%m/%d'),
        ),
    ]
